{% set version = "4.26.0" %}

package:
  name: selenium-manager
  version: {{ version }}

source:
  url: https://github.com/SeleniumHQ/selenium/archive/refs/tags/selenium-{{ version }}.tar.gz
  sha256: 593af8abafbdf98fcac4dc35938a9cddae148b5096b584b69b97a7ca190c8fdf

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
  host: []

test:
  commands:
    - selenium-manager --version
    - selenium-manager --help
    - '"${SE_MANAGER_PATH}" --version'  # [not win]
    - '%SE_MANAGER_PATH% --version'  # [win]

about:
  home: https://github.com/SeleniumHQ/selenium
  license: Apache-2.0
  license_file:
    - THIRDPARTY.yml
    - LICENSE
    - NOTICE
  summary: |-
    Selenium Manager is a standalone tool that automatically manages the browser
    infrastructure required by Selenium (i.e., browsers and drivers).

extra:
  recipe-maintainers:
    - conda-forge/selenium
    - bollwyvl
